# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          apt-get -y install git perl curl wget ant ant-contrib build-essential
      # Runs a set of commands using the runners shell
      - name: Clone aqa
        run: |
          git clone https://github.com/adoptium/aqa-tests.git
          cd aqa-tests
          ./get.sh --customizedURL https://javabinaires.blob.core.windows.net/newcontainer/jdk17u.tar.gz
          cd TKG
          make genParallelList PARALLEL_OPTIONS="TEST=extended TEST_TIME=3 NUM_MACHINES="

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-output-parallellist
          path: /aqa-tests/TKG/parallelList.mk