name: Dynamic

on:
  workflow_dispatch:
    inputs:
      runners:
        description: Runners 
        required: false
        default: 4
      runner:
        description: runner
        required: true
        default: ubuntu

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ steps.config.outputs.x }}
      runner: ${{ steps.config.outputs.runner }}
    steps:
    - name: configure runners
      id: config
      run: |
        import os
        import json

        num_lists = ${{ inputs.runners }}
        test_lists = []

        for list in range(num_lists):
          test_lists.append(f"testItem_{list}")
        
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f"x={json.dumps(test_lists)}", file=fh)

        if ${{ inputs.runner }} == 'ubuntu':
          github_runner = "runner='ubuntu-latest'"
        elif ${{ inputs.runner }} == "macos":
          github_runner = "runner='macos-latest'"
        else:
          github_runner = "runner='windows-latest'"
        
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(github_runner, file=fh)
        
      shell: python
  
  run:
    needs: [configure]
    name: Run
    runs-on: ${{ fromJSON(needs.configure.outputs.runner) }}
    strategy:
      fail-fast: true
      matrix:
        test: ${{ fromJSON(needs.configure.outputs.configuration) }}
        suite: [1,2,3,4]
      
    steps:
      - name: run job
        run:
          echo ${{ matrix.test }} ---- ${{ matrix.suite }}